package GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author reych
 */
public class SegundoFrame extends javax.swing.JFrame {

    /**
     * Creates new form SegundoFrame
     */
    public SegundoFrame() {
        initComponents();
        this.btnGroup.add(rbtOption1);
        this.btnGroup.add(rbtOption2);
        this.btnGroup.add(rbtOption3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        rbtOption1 = new javax.swing.JRadioButton();
        rbtOption2 = new javax.swing.JRadioButton();
        rbtOption3 = new javax.swing.JRadioButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uso de Radio Button");

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccionar una imagen");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        rbtOption1.setText("Opcion 1");
        rbtOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOption1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(rbtOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 105, -1, -1));

        rbtOption2.setText("Opcion 2");
        rbtOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOption2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(rbtOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 137, -1, -1));

        rbtOption3.setText("Opcion 3");
        rbtOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOption3ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(rbtOption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 175, -1, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jDesktopPane1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 190, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOption1ActionPerformed
       lblImage.setIcon(new ImageIcon(getClass().getResource(
               "/images/1.png")));
    }//GEN-LAST:event_rbtOption1ActionPerformed

    
    private void rbtOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOption2ActionPerformed
  lblImage.setIcon(new ImageIcon(getClass().getResource(
               "/images/2.png")));
    }//GEN-LAST:event_rbtOption2ActionPerformed

    private void rbtOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOption3ActionPerformed
  lblImage.setIcon(new ImageIcon(getClass().getResource(
               "/images/3.png")));

    }//GEN-LAST:event_rbtOption3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JRadioButton rbtOption1;
    private javax.swing.JRadioButton rbtOption2;
    private javax.swing.JRadioButton rbtOption3;
    // End of variables declaration//GEN-END:variables
}
